import {
  emptyScene,
  waitingActions,
  type Context,
  type Scene,
} from './scene.ts';
export type DemoCase = {
  id: string;
  title: string;
  name?: string;
  understanding?: string;
  input: string;
  entry: 'ambient' | 'create' | 'counter';
  category: string;
  summary: string;
  family?: string;
  reply?: string;
  question?: string;
  kind?: 'control' | 'chat' | 'clarify' | 'preset' | 'blocked';
  actions?: [string, string][];
  conditions?: [string, string, string?][];
  say?: string;
  initial?: Record<string, string>;
};
export const DEMO_CASES: DemoCase[] = [
  {
    id: 'ambient-wait',
    title: '还要等一会儿',
    input: '她说还要二十分钟',
    entry: 'ambient',
    category: '等人与休息',
    family: 'wait',
    summary: '回应之后，轻问一句是否布置等待空间。',
    reply: '那就先歇一会儿，不着急。',
    question: '要把这会儿布置舒服些吗？',
  },
  {
    id: 'ambient-rear',
    title: '后排睡着了',
    input: '后排已经睡着了',
    entry: 'ambient',
    category: '家庭乘坐',
    family: 'rear',
    summary: '声音留在前排，减少光线打扰。',
    reply: '嗯，让后排安静休息。',
    question: '要把声音和灯光收一点吗？',
    actions: [
      ['声场', '前排模式'],
      ['音量', '20%'],
      ['氛围灯亮度', '20%'],
    ],
  },
  {
    id: 'ambient-meeting',
    title: '会前的半小时',
    input: '我到地方了，离开会还有半小时',
    entry: 'ambient',
    category: '等人与休息',
    family: 'meeting',
    summary: '安静的声场与适合看屏幕的亮度。',
    reply: '还有点时间，可以慢慢准备。',
    question: '要留一会儿安静准备吗？',
    actions: [
      ['声场', '主驾模式'],
      ['音量', '10%'],
      ['屏幕亮度', '60%'],
    ],
  },
  {
    id: 'ambient-dust',
    title: '窗外在施工',
    input: '窗外在施工，灰都飘进来了',
    entry: 'ambient',
    category: '空气环境',
    family: 'dust',
    summary: '关窗、内循环与净化；先确认，再应用。',
    reply: '外面的灰尘确实让人不舒服。',
    question: '要关窗并净化一下空气吗？',
    initial: { 主驾车窗: '20%' },
    actions: [
      ['主驾车窗', '关闭'],
      ['内外循环设置', '内循环'],
      ['自动空气净化', '开启'],
    ],
  },
  {
    id: 'ambient-sun',
    title: '晒了一下午',
    input: '车在太阳下晒了一下午，座椅都是烫的',
    entry: 'ambient',
    category: '空气环境',
    family: 'sun',
    summary: '针对日晒处境安排遮阳和座椅通风。',
    reply: '先让座椅和车里慢慢凉下来。',
    question: '要遮阳并给座椅通风吗？',
    initial: { 电动遮阳帘: '100%', 主驾温度控制: '28℃' },
    actions: [
      ['电动遮阳帘', '关闭'],
      ['主驾座椅通风', '3挡'],
      ['主驾温度控制', '22℃'],
    ],
  },
  {
    id: 'ambient-long',
    title: '还有一段长路',
    input: '这趟路还挺长的',
    entry: 'ambient',
    category: '旅途',
    family: 'long',
    summary: '声音与空气安排，不读取不存在的导航剩余距离。',
    reply: '路还长，按自己的节奏走。',
    question: '要让车里清爽安静一点吗？',
    actions: [
      ['自动空气净化', '开启'],
      ['音量', '20%'],
      ['出风模式设置', '吹面吹脚'],
    ],
  },
  {
    id: 'ambient-rest',
    title: '终于停下来了',
    input: '今天连着开了几个小时，刚停下来，有点累',
    entry: 'counter',
    kind: 'chat',
    category: '等人与休息',
    family: 'rest',
    summary: '疲劳先休息；需要休憩模式时可直接点名进入。',
    reply: '辛苦了，停下来歇一歇。',
    question: '要不要开休憩模式？',
  },
  {
    id: 'ambient-en',
    title: 'A little waiting time',
    input: 'We still have twenty minutes to wait.',
    entry: 'ambient',
    category: '等人与休息',
    family: 'wait',
    summary: '英文处境走同一条主动询问路径。',
    reply: 'There is time to settle in.',
    question: 'Make this wait a little more comfortable?',
  },
  {
    id: 'direct-simple',
    title: '直接调灯与温度',
    input: '把灯调暗、温度24度',
    entry: 'counter',
    category: '交给车控',
    kind: 'control',
    summary: '已经说清具体动作，车控直接完成，不生成场景。',
    actions: [
      ['氛围灯亮度', '20%'],
      ['主驾温度控制', '24℃'],
    ],
  },
  {
    id: 'direct-hot',
    title: '太热了',
    input: '热死了',
    entry: 'counter',
    category: '交给车控',
    kind: 'control',
    summary: '冷热是单项舒适调控，不应主动拼一组场景。',
    actions: [['MAX AC', '开启']],
  },
  {
    id: 'direct-mode',
    title: '进入露营模式',
    input: '进入露营模式',
    entry: 'counter',
    category: '官方预设',
    kind: 'preset',
    summary: '车机已有模式直接进入，不重新编排场景。',
    actions: [['进入情景模式', '露营模式']],
  },
  {
    id: 'direct-recording',
    title: '进入录音模式',
    input: '进入录音模式',
    entry: 'counter',
    category: '直接车控',
    kind: 'preset',
    summary: '打开车机已有录音功能；不新增场景原子能力。',
  },
  {
    id: 'chat-traffic',
    title: '又堵车了',
    input: '又堵了，烦死了',
    entry: 'counter',
    category: '只回应',
    kind: 'chat',
    summary: '车改善不了拥堵，在可改善性判断处停止。',
    reply: '堵在路上确实烦，慢慢来，注意前方。',
  },
  {
    id: 'ambient-emotion',
    title: '心情不好',
    input: '今天心情很不好',
    entry: 'ambient',
    category: '情绪与陪伴',
    family: 'mood',
    name: '缓一缓',
    summary: '用柔和灯光和较低音量留一点安静，确认后再调整。',
    understanding: '把光和声音放轻些，留一点安静。',
    reply: '先给自己一点安静的时间。',
    actions: [
      ['氛围灯亮度', '20%'],
      ['音量', '20%'],
    ],
  },
  {
    id: 'ambient-anniversary',
    title: '今天是纪念日',
    input: '今天是我们的纪念日',
    entry: 'ambient',
    category: '情绪与陪伴',
    family: 'anniversary',
    name: '特别的今天',
    summary: '柔和灯光与浪漫音乐组成纪念日建议，音乐能力标注提议中。',
    understanding: '柔和的光，配一点浪漫的旋律。',
    reply: '给这个特别的日子，一点仪式感。',
    actions: [
      ['氛围灯亮度', '40%'],
      ['音量', '20%'],
      ['音乐播放', '浪漫'],
    ],
  },
  {
    id: 'ambient-unwind-en',
    title: 'Time to unwind',
    name: 'Unwind',
    input: "It's been a long day. I could use a quiet moment.",
    entry: 'ambient',
    category: '情绪与陪伴',
    family: 'unwind',
    summary: '英文情境建议：降低声音与灯光，给漫长的一天留一段缓冲。',
    understanding: 'Softer light, a quieter moment.',
    reply: 'Take a moment for yourself.',
    actions: [
      ['氛围灯亮度', '20%'],
      ['音量', '20%'],
    ],
  },
  {
    id: 'chat-sleepy',
    title: '行驶中犯困',
    input: '开车有点困',
    entry: 'counter',
    category: '只回应',
    kind: 'chat',
    summary: '不营造放松或助眠氛围，提醒安全停车休息。',
    reply: '请在安全位置停车休息，别勉强继续开。',
  },
  {
    id: 'direct-clarify',
    title: '对象没说清',
    input: '帮我把那个打开',
    entry: 'counter',
    category: '先问清楚',
    kind: 'clarify',
    summary: '明确对象后交给车控，不凭空创建场景。',
    question: '你想打开空调、灯光，还是车窗？',
  },
  {
    id: 'direct-forbidden',
    title: '警报音不能关闭',
    input: '关闭行人警报音',
    entry: 'counter',
    category: '不执行',
    kind: 'blocked',
    summary: '禁止值不能执行，也不能绕过规则存成场景。',
    reply: '行人警报音不能关闭。',
  },
  {
    id: 'rain',
    title: '雨夜归途',
    input: '做一个雨夜回家的场景',
    entry: 'create',
    category: '通勤与旅途',
    family: 'rain',
    summary: '除雾、灯光、温度与雨天音乐，天气条件为提议。',
    conditions: [
      ['时段', '夜晚'],
      ['天气', '雨'],
      ['位置', '家'],
    ],
    actions: [
      ['前风窗除雾', '开启'],
      ['氛围灯亮度', '30%'],
      ['主驾温度控制', '24℃'],
      ['音乐播放', '雨天'],
    ],
  },
  {
    id: 'wait',
    title: '等你的片刻',
    input: '等人时，帮我布置得舒服一点',
    entry: 'create',
    category: '休息与专注',
    family: 'wait',
    summary: '按档案安排灯光、声音与温度。',
  },
  {
    id: 'quiet',
    title: '后排轻声',
    input: '做个安静场景，别吵醒后排',
    entry: 'create',
    category: '家庭乘坐',
    family: 'rear',
    summary: '用安全带作有人代理，声场与灯光共同减扰。',
    conditions: [['右后排安全带', '系上']],
    actions: [
      ['声场', '前排模式'],
      ['音量', '20%'],
      ['氛围灯亮度', '20%'],
    ],
  },
  {
    id: 'winter',
    title: '冬日暖座',
    input: '做一个冬天上车暖座的场景',
    entry: 'create',
    category: '季节与定时',
    summary: '日期范围内，座椅、方向盘与温度一起准备。',
    conditions: [
      ['日期区间', '20261201-20270228'],
      ['挡位', '挡位P'],
    ],
    actions: [
      ['主驾座椅加热', '2挡'],
      ['方向盘加热', '开启'],
      ['主驾温度控制', '26℃'],
    ],
  },
  {
    id: 'commute',
    title: '早间出发',
    input: '工作日早上七点半，给我准备一个出发场景',
    entry: 'create',
    category: '季节与定时',
    summary: '精确时间与重复周期，配合屏幕、温度和天气播报。',
    conditions: [
      ['生效时间', '07:30'],
      ['重复周期', '工作日'],
    ],
    actions: [
      ['屏幕模式', '白天模式'],
      ['主驾温度控制', '22℃'],
      ['小塔播报', '播放天气'],
    ],
  },
  {
    id: 'family',
    title: '后排暖一点',
    input: '给后排做一个冬天乘车更舒服的场景',
    entry: 'create',
    category: '家庭乘坐',
    summary: '左右后排加热与前排声场，避免把所有乘员混成一份设置。',
    actions: [
      ['左后排座椅加热', '1挡'],
      ['右后排座椅加热', '1挡'],
      ['声场', '前排模式'],
      ['温区同步', '开启'],
    ],
  },
  {
    id: 'cinema',
    title: '停车小影院',
    input: '停车等人时，做个看视频的场景',
    entry: 'create',
    category: '娱乐与庆祝',
    summary: '视频应用标规划中，搭配影院音效、音量和屏幕亮度。',
    conditions: [['挡位', '挡位P']],
    actions: [
      ['腾讯视频', '打开'],
      ['音效', '影院'],
      ['音量', '30%'],
      ['屏幕亮度', '70%'],
    ],
  },
  {
    id: 'karaoke',
    title: '露营唱一首',
    input: '露营时做一个K歌场景',
    entry: 'create',
    category: '娱乐与庆祝',
    summary: '停车后使用 K 歌、全车声场和音乐律动，K 歌为规划能力。',
    conditions: [['挡位', '挡位P']],
    actions: [
      ['唱吧', '打开'],
      ['声场', '全车模式'],
      ['音量', '40%'],
      ['音乐律动', '模式1'],
    ],
  },
  {
    id: 'camp',
    title: '自己的露营方式',
    input: '做个露营场景，屏幕暗些，声音留在全车',
    entry: 'create',
    category: '娱乐与庆祝',
    summary: '官方露营预设作为基础，再加你自己的屏幕与声音设置。',
    conditions: [['挡位', '挡位P']],
    actions: [
      ['进入情景模式', '露营模式'],
      ['屏幕亮度', '30%'],
      ['声场', '全车模式'],
      ['音量', '20%'],
    ],
  },
  {
    id: 'birthday',
    title: '明确说出的庆祝',
    input: '帮我做个生日庆祝场景，10月1日用',
    entry: 'create',
    category: '娱乐与庆祝',
    summary: '指定日期、生日动效和灯光；明确请求才安排庆祝音乐。',
    conditions: [
      ['指定日期', '20261001'],
      ['挡位', '挡位P'],
    ],
    actions: [
      ['彩蛋', '生日动效'],
      ['氛围灯亮度', '70%'],
      ['音乐播放', '庆祝'],
    ],
  },
  {
    id: 'fragrance',
    title: '淡淡的香气',
    input: '做个有淡淡香气的休息场景',
    entry: 'create',
    category: '休息与专注',
    summary: '香氛、灯光与声音；不喜欢香氛的档案会裁掉香氛。',
    actions: [
      ['香氛开关', '开启'],
      ['香氛浓度', '淡雅'],
      ['氛围灯亮度', '30%'],
      ['音量', '10%'],
    ],
  },
  {
    id: 'reading',
    title: '晚间阅读',
    input: '做个停车读书的场景，别太亮',
    entry: 'create',
    category: '休息与专注',
    summary: '灯光、屏幕与低音量；按摩档位不在当前能力表里，不凑这一项。',
    conditions: [['挡位', '挡位P']],
    actions: [
      ['氛围灯亮度', '40%'],
      ['屏幕亮度', '30%'],
      ['音量', '0%'],
    ],
  },
  {
    id: 'dust',
    title: '把灰尘留在外面',
    input: '做一个外面扬尘时用的车内净化场景',
    entry: 'create',
    category: '空气与日晒',
    summary: '手动使用，组合关窗、内循环、净化与出风；不发明扬尘传感器。',
    actions: [
      ['主驾车窗', '关闭'],
      ['副驾车窗', '关闭'],
      ['内外循环设置', '内循环'],
      ['自动空气净化', '开启'],
      ['前排风量调节', '3挡'],
    ],
  },
  {
    id: 'sun',
    title: '日晒后的片刻',
    input: '做个暴晒后上车降温的场景',
    entry: 'create',
    category: '空气与日晒',
    summary: '遮阳帘、座椅通风、温度和风量，不只重复灯光音量。',
    actions: [
      ['电动遮阳帘', '关闭'],
      ['主驾座椅通风', '3挡'],
      ['主驾温度控制', '22℃'],
      ['前排风量调节', '4挡'],
    ],
  },
  {
    id: 'meeting',
    title: '会前准备',
    input: '做个停车开会前安静准备的场景',
    entry: 'create',
    category: '休息与专注',
    summary: '主驾声场、低媒体音量与清晰屏幕；不假装接入会议软件。',
    conditions: [['挡位', '挡位P']],
    actions: [
      ['声场', '主驾模式'],
      ['音量', '10%'],
      ['屏幕亮度', '60%'],
      ['语音音量', '20%'],
    ],
  },
  {
    id: 'weekend',
    title: '周末换个样子',
    input: '做一个周末用的明亮屏幕场景',
    entry: 'create',
    category: '季节与定时',
    summary: '周末生效范围配合屏幕和自定义主题；主题为概念展示。',
    conditions: [['重复周期', '周末']],
    actions: [
      ['屏幕模式', '白天模式'],
      ['屏幕亮度', '70%'],
      ['氛围灯亮度', '50%'],
      ['主题', '远山'],
    ],
  },
  {
    id: 'pickup',
    title: '停车迎接',
    input: '做个停车接人场景，打开左后门，后排暖一点',
    entry: 'create',
    category: '家庭乘坐',
    summary: '车门在当前能力表里只作条件、不作动作，开门交给车控；场景保留后排加热与灯光。',
    conditions: [['挡位', '挡位P']],
    actions: [
      ['左后排座椅加热', '1挡'],
      ['氛围灯亮度', '60%'],
    ],
  },
  {
    id: 'planned',
    title: '晚间旋律',
    input: '每天19点，播放QQ音乐我喜欢的列表',
    entry: 'create',
    category: '季节与定时',
    summary: '定时和重复周期组合，歌单为规划中。',
    conditions: [
      ['生效时间', '19:00'],
      ['重复周期', '每天'],
    ],
    actions: [['QQ音乐', '我喜欢列表']],
  },
  {
    id: 'song',
    title: '这一首歌',
    input: '做个停车放Here Comes the Sun的场景',
    entry: 'create',
    category: '娱乐与庆祝',
    summary: '具体歌名保留完整参数，配合灯光与音量；播放指定音乐为规划中。',
    conditions: [['挡位', '挡位P']],
    actions: [
      ['播放指定音乐', 'Here Comes the Sun'],
      ['音量', '30%'],
      ['氛围灯亮度', '50%'],
    ],
  },
  {
    id: 'english',
    title: 'Quiet moment',
    input: 'Create a quiet scene for waiting in the car',
    entry: 'create',
    category: '休息与专注',
    family: 'wait',
    summary: '英文输入，同样参考档案并支持局部续改。',
  },
  {
    id: 'simple',
    title: '光和温度',
    input: '做一个光和温度的场景',
    entry: 'create',
    category: '休息与专注',
    summary: '明确要求保留组合，才创建场景。',
    actions: [
      ['氛围灯亮度', '20%'],
      ['主驾温度控制', '24℃'],
    ],
  },
  {
    id: 'sequence',
    title: '先清爽，再安静',
    input: '做个先净化空气，五秒后把音量放低的场景',
    entry: 'create',
    category: '空气与日晒',
    summary: '先开启净化，等待五秒，再降低音量，保留动作顺序。',
    actions: [
      ['自动空气净化', '开启'],
      ['延时', '5秒'],
      ['音量', '10%'],
    ],
  },
  {
    id: 'boundary-color',
    title: '亮度可以，颜色不行',
    input: '做个蓝色氛围灯的安静场景',
    entry: 'create',
    category: '不支持的请求',
    summary: '没有灯光颜色接口；可安排声音，颜色请求明确保留为不支持。',
    actions: [['音量', '20%']],
  },
  {
    id: 'boundary-distance',
    title: '这个触发条件还做不了',
    input: '做一个到家前1公里调暗灯光的场景',
    entry: 'create',
    category: '不支持的请求',
    summary: '导航剩余距离已删除，不能删掉这个条件后假装可保存。',
    actions: [['氛围灯亮度', '20%']],
  },
  {
    id: 'boundary-safety',
    title: '安全限制也会保留',
    input: '做个透气场景，车窗开到50%，关闭行人警报音',
    entry: 'create',
    category: '不支持的请求',
    summary: '行人警报音禁止关闭；行驶时车窗最多20%，原值与调整原因同时显示。',
    actions: [
      ['主驾车窗', '50%'],
      ['低速行人警报音', '关闭'],
    ],
  },
];
export function demoCase(id: string) {
  return DEMO_CASES.find((c) => c.id === id);
}
export function sceneForCase(id: string, ctx: Context, input?: string): Scene {
  const c = demoCase(id);
  if (!c) throw new Error('未知示例');
  const waiting: [string, string][] = waitingActions(ctx).map((a) => [
    a.primary,
    a.secondary,
  ]);
  const en = /^[\x20-\x7E\s]*$/.test(input || c.input);
  const feeling: Record<string, string> = {
    wait: '把这段等待，留给自己',
    rain: '让雨夜的这一段路，清晰又安稳',
    quiet: '声音留在前排，安静留给后排',
    winter: '从方向盘到座椅，慢慢暖起来',
    commute: '到出发的时候，让车里准备妥当',
    family: '把舒适也留给坐在后排的人',
    cinema: '停下来，留一点看电影的时间',
    karaoke: '让歌声和灯光一起陪你',
    camp: '在你自己的露营方式里多待一会儿',
    birthday: '为明确说出的庆祝，安排一个特别的时刻',
    fragrance: '一缕淡香，轻一点的光和声',
    reading: '把这一刻留给书页',
    dust: '把灰尘留在窗外，让车内空气清爽些',
    sun: '挡住日晒，让座椅和车里慢慢凉下来',
    meeting: '给即将开始的会议，留一段安静的准备',
    weekend: '从明亮的屏幕开始周末',
    pickup: '停稳之后，让后排温暖地迎接来人',
    planned: '到这个时刻，留一段喜欢的旋律',
    song: '让这一首熟悉的歌，陪你待一会儿',
    simple: '留下你说的光和温度',
    sequence: '先换来清爽，再慢慢安静下来',
    'boundary-distance': '这个到家前的触发条件，还需要换一种方式',
    'boundary-color': '声音可以安静下来，灯光颜色暂时还做不了',
  };
  return {
    ...emptyScene(),
    intent:
      c.entry === 'create'
        ? 'precise'
        : ['mood', 'anniversary', 'unwind'].includes(c.family || '')
          ? 'affect'
          : 'vague',
    relevance: ['mood', 'anniversary', 'unwind'].includes(c.family || '')
      ? 0.5
      : 0.9,
    name:
      c.name ||
      (c.family === 'wait' ? (en ? 'Quiet moment' : '等你的片刻') : c.title),
    understanding:
      c.understanding ||
      (en
        ? `“${input || c.input}” — a little less light, a comfortable space to wait.`
        : `${feeling[c.id] || (c.family === 'wait' ? feeling.wait : c.question?.replace(/要|吗？/g, '') || c.title)}。`),
    conditions: (c.conditions || []).map(([primary, secondary, op]) => ({
      primary,
      secondary,
      op: op || '==',
    })),
    actions: (c.actions || waiting).map(([primary, secondary]) => ({
      primary,
      secondary,
    })),
    say: c.say || '',
    unsupported: c.id === 'boundary-color' ? ['氛围灯改成蓝色'] : [],
  };
}
